### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Muto1899** [escalate/loxone-ha-bridge-importer#1]
Hi,

I´d like to include your script into the Loxberry HaBridge Plugin

http://www.loxwiki.eu/display/LOXBERRY/LoxBerry

Could you please create a release so I can include the download of a stable source version.

Thanks, Muto

**Comment by escalate** [comment]
Hi Muto,

your idea sounds great. 
I need some time to create a release because this tool is still under development.
Could you please use the last git hash ad224f943e3c7e8d7f5ee94f2ea8ca765ec8f664 for the moment?

Greetings
Felix

**Comment by Muto1899** [comment]
Hi Felix,

thanks, will do so.

**Comment by escalate** [comment]
Hi Muto,

I created an release.

https://github.com/escalate/loxone-ha-bridge-importer/releases/tag/v1.0.0

I hope that helps you.
