### ISSUE TITLE
Lichtsteuerungen mit auslesen

### ISSUE THREAD

**Issue by beeper77** [escalate/loxone-ha-bridge-importer#2]
Hallo,

vielleicht habe ich etwas falsch verstanden, aber bei mir wurden die Lichtsteuerungen nicht mit beachtet. Wenn ich hier in der Doku schaue sind die dort auch nicht mit aufgelistet. Besteht die Change diese rudimentär mit einzulesen? Also pro Szene ein Einschalten und ein gemeinsames Ausschalten. Technisch wäre es doch eigentlich möglich.
Danke

**Comment by escalate** [comment]
Hallo @beeper77,
die Lichtsteuerung wird aktuell nicht ausgewertet. Da ich diese selbst nicht nutze habe ich sie auch nicht richtig implementieren und testen können.
Aber ich kann sie gern mit einbauen.
Kannst du mir dazu bitte die WARNING Meldungen vom Kommando-Aufruf in diesen Issue schreiben?
Dort stehen alle Loxone Controls die durch das Script nicht ausgewertet werden.
Ich benötige die Namen damit ich diese einbauen kann.
Prima wäre auch noch, wenn du mir sagen könntest, was passieren soll, wenn Alexa den On-, Off- bzw. Dim-Befehl sendet.
Beste Grüße
Felix

**Comment by beeper77** [comment]
Hallo,
das Warning sieht wie folgt aus:
WARNING: Control type "LightController" is not supported at the moment.
Der LightController hat ja sowohl Szenen, als auch normale Ausgänge. Die Szenen mischen ja die Ausgänge und sind daher wichtiger als die tatsächlichen Ausgänge. Szene 0 ist immer alles Aus.

Wenn ich es richtig im Kopf habe, wird die ID des Lightcontrollers genutzt. In der Loxone Datei sieht das dann so aus:
<C Type="LightController" V="99" U="0b39c6f9-00d2-33be-ffff112233445566" Title="
Für einen AN Befehl wird dann einfach die Szenennummer angegeben (für Szene 1):
http://miniserver/dev/sps/io/0b325474-009c-70fe-ffff114564445566/1

Ein AUS wäre dann einfach Szene 0:
http://miniserver/dev/sps/io/0b325474-009c-70fe-ffff114564445566/0

Für Dimmen kann dann das hier genutzt werden:
http://miniserver/dev/sps/io/0b320074-009c-70fe-ffff112233445566/AI1/50
für 50% gedimmt.

Wo ich mir nun nicht sicher bin, ist allerdings, wie am Besten unterschieden werden kann ob es ein Dimmbarer Ausgang ist oder nicht.
Gruß,
Volker

**Comment by beeper77** [comment]
Hallo,

@escalate ich wollte einmal nachfragen, ob du die Erweiterung machen möchtest. Sonst, was natürlich kein Problem wäre, müsste ich mir etwas anderes überlegen.
Danke dir

**Comment by escalate** [comment]
Hallo @beeper77,

ich habe einen "alles ein" und einen "komplett aus" Mechanismus eingebaut.
Von diesem Punkt kann man dann gut in der HA Bridge weiter arbeiten und modifizieren.

Beste Grüße
Felix
