### ISSUE TITLE
Please Add Loxone LightControllerV2

### ISSUE THREAD

**Issue by eloka080677** [escalate/loxone-ha-bridge-importer#3]
Dear escalate,

can you please add the Loxone LightcontrollerV2 to the importer.py ?

Generate HA-Bridge devices configruation from visualisation structure file
WARNING: Control type "LightControllerV2" is not supported at the moment.

Thank you a lot

**Comment by escalate** [comment]
Hello eloka080677

I added the LightcontrollerV2 control with plus and minus command.
I hope this is a good default for start.
I would appreciate a feedback from you.

For more details about the commands of the LightcontrollerV2 please take a look at the documentation.
https://www.loxone.com/dede/wp-content/uploads/sites/2/2018/10/1000_Structure-File.pdf
