### ISSUE TITLE
Befehl / Eingabe bei HA-Bridge auf Port 80?

### ISSUE THREAD

**Issue by Dizzy1985** [escalate/loxone-ha-bridge-importer#4]
Wie muss die Eingabe / Befehl aussehen wenn die Ha-Bridge auf Port 80 läuft?

--ha-bridge-port INTEGER  Set port of HA-Bridge server (Default: 8080)
                            [required]

Wenn ich folgendes eingebe:

 --ha-bridge-port ="80" \

bekomme ich folgende Fehlermeldung:
Error: Invalid value for "--ha-bridge-port": =80 is not a valid integer

**Comment by escalate** [comment]
Hallo @Dizzy1985,
es fehlte die Typisierung der Options.
Diese habe ich nun ergänzt
Beste Grüße
Felix

**Comment by Dizzy1985** [comment]
root@loxberry:/opt/loxone-ha-bridge-importer# python3 importer.py \
> --loxone-miniserver="XXX.XXX.X.XX" \
> --loxone-username="XXXXX" \
> --loxone-password="XXXXX" \
> --ha-bridge-server ="192.168.0.22" \
> --ha-bridge-port =80
Usage: importer.py [OPTIONS]
Try "importer.py --help" for help.

Error: Invalid value for "--ha-bridge-port": =80 is not a valid integer

Ist leider immer noch das selbe, der Port wird nicht akzeptiert????

**Comment by escalate** [comment]
Hallo @Dizzy1985,
ich denke das Leerzeichen vor dem **=** verursacht das Problem.
`--ha-bridge-port =80`
Du kannst es entweder ohne **=** oder eben ohne Leerzeichen vor dem **=** schreiben.
`--ha-bridge-port 80` oder `--ha-bridge-port=80`
Beste Grüße

**Comment by Dizzy1985** [comment]
Funktioniert ;-)
