### ISSUE TITLE
ConnectTimeout

### ISSUE THREAD

**Issue by Trebron123** [escalate/loxone-ha-bridge-importer#5]
Ich bekomme immer u.a. folgende Meldung: 
HTTPConnectionPool(host='192.168.1.x', port=80): Max retries exceeded with url: /data/LoxAPP3.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75e7f190>, 'Connection to 192.168.1.x timed out. (connect timeout=5)'))
-bash: syntax error near unexpected token `('

Mein MS läuft auf Port 7777. Bin auch nicht besonders fit in diesen Sachen.

**Comment by escalate** [comment]
Hallo,

ich habe das Problem verstanden. Dafür muss ich das Python Programm erweitern.

Beste Grüße
Felix

**Comment by Trebron123** [comment]
Klasse! Danke!


Mit freundlichen Grüßen


N. Langer

nl@nlanger.eu
0049 1718165000
0049 251 931493
0049 251 931494
___________________
Lohausweg 24
48145 Münster

**Comment by escalate** [comment]
Ist es möglich die Loxone /data/LoxAPP3.json zu erhalten? Ich würde mir gern die Detail ansehen.

**Comment by Trebron123** [comment]
Hallo, Felix

 

Vielen Dank für die schnelle Reaktion. Im Pfad /opt/loxone-ha-bridge-importer/tests/fixtures habe ich beiliegende Dateien gefunden.

 

 

Mit freundlichen Grüßen


N. Langer

nl@nlanger.eu <mailto:nl@nlanger.eu> 
0049 1718165000
0049 251 931493
0049 251 931494
___________________
Lohausweg 24
48145 Münster 

 

 

Von: Felix Börner <notifications@github.com> 
Gesendet: Mittwoch, 8. April 2020 21:16
An: escalate/loxone-ha-bridge-importer <loxone-ha-bridge-importer@noreply.github.com>
Cc: Trebron123 <nl@nlanger.eu>; Author <author@noreply.github.com>
Betreff: Re: [escalate/loxone-ha-bridge-importer] ConnectTimeout (#5)

 

Ist es möglich die Loxone /data/LoxAPP3.json zu erhalten? Ich würde mir gern die Detail ansehen.

**Comment by Trebron123** [comment]
Ich habe auch noch diese Datei gefunden.

 

 

 

Mit freundlichen Grüßen


N. Langer

nl@nlanger.eu <mailto:nl@nlanger.eu> 
0049 1718165000
0049 251 931493
0049 251 931494
___________________
Lohausweg 24
48145 Münster 

 

 

Von: Felix Börner <notifications@github.com> 
Gesendet: Mittwoch, 8. April 2020 21:16
An: escalate/loxone-ha-bridge-importer <loxone-ha-bridge-importer@noreply.github.com>
Cc: Trebron123 <nl@nlanger.eu>; Author <author@noreply.github.com>
Betreff: Re: [escalate/loxone-ha-bridge-importer] ConnectTimeout (#5)

 

Ist es möglich die Loxone /data/LoxAPP3.json zu erhalten? Ich würde mir gern die Detail ansehen.
