### ISSUE TITLE
Error: Missing option "--loxone-miniserver-host".

### ISSUE THREAD

**Issue by Trebron123** [escalate/loxone-ha-bridge-importer#6]
Ich erhalte die obige Meldung. Was muss ich angeben?

**Comment by escalate** [comment]
Hallo @Trebron123,
hast du bereits die README.md im Punkt Usage gelesen?
`--loxone-miniserver-host TEXT    Set IP address / hostname of Loxone MiniServer  [required]`
Beste Grüße
Felix

**Comment by Trebron123** [comment]
Alles klar, danke, gucke ich gleich noch mal nach.

Mit freundlichen Grüßen


N. Langer

nl@nlanger.eu
0049 1718165000
0049 251 931493
0049 251 931494
___________________
Lohausweg 24
48145 Münster

**Comment by Trebron123** [comment]
Super! Funktioniert!

Mit freundlichen Grüßen


Norbert
